### ISSUE TITLE
Rule failing with latest eslint-plugin-vue

### ISSUE THREAD

**Issue by davydnorris** [vuetifyjs/eslint-config-vuetify#14]
This rule is failing on the following line in the latest release of eslint-plugin-vue. Looks like they may have removed the option

https://github.com/vuetifyjs/eslint-config-vuetify/blob/a3f82f37526c5dcf7d0c254222c59a76d9cc6ec2/index.js#L32

looking at the code, it appears it was never there despite being in the documentation

**Comment by MartinX3** [comment]
This project seems to be dead.
Please use https://github.com/vuetifyjs/eslint-plugin-vuetify and the `extends` `plugin:vuetify/recommended`

**Comment by davydnorris** [comment]
I found the issue - they've removed the option into a new rule. See:
[https://github.com/vuejs/eslint-plugin-vue/pull/1587](https://github.com/vuejs/eslint-plugin-vue/pull/1587)

Correct rule should now be:

```
'vue/max-attributes-per-line': ['error', {
  singleline: 1,
  multiline: 1,
}],
'vue/first-attribute-linebreak': ['error', {
  'singleline': 'beside',
  'multiline': 'below',
}],
```
