### ISSUE TITLE
Was this bump to eslint 7 needed?

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/eslint-config-vuetify#6]
https://github.com/vuetifyjs/eslint-config-vuetify/blob/bb9c32d66bd68b5e1b4704dc39236c12c2206a7d/package.json#L18

It put one of my projects into a bind where other plugins and configs were restricting to `^6` and `^5` and with this now `^7`

![image](https://user-images.githubusercontent.com/44366456/82449466-1a7a9300-9a60-11ea-8e08-1c3b2ec7e4a1.png)

It breaks when I ran ` yarn add -D eslint eslint-config-vuetify eslint-plugin-vuetify`

here is a portion of my package.json too
```
    "eslint-config-node": "^4.0.0",
    "eslint-config-prettier": "^6.7.0",
    "eslint-config-vuetify": "^0.6.1",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jest": "^23.0.3",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-promise": "^4.1.1",
    "eslint-plugin-simple-import-sort": "^4.0.0",
    "eslint-plugin-vue": "^6.0.1",
```

**Comment by KaelWD** [comment]
You might be looking for https://github.com/vuetifyjs/eslint-plugin-vuetify, this config is for consistent formatting between our internal projects.
